modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="allmods"
version="1.0.0"
displayName="AllMods18.0"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pures, MCreator"

[[dependencies.allmods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




